[workspace]
members =[
  "helloword",
  "helloword2",
  "r3struct1",
  "r3array",
  "r4match",
  "r5method",
  "r6generic",
  "r7trait",
  "r8lifetime",
  "r9iterator",
  "r10box",
  "r11cell",
  "r12thread",
  "r13channel",
  "r14condlock"
]
