[package]
name = "z_4_2_closure"
version = "0.1.0"
authors = ["lpxxn <mi_duo@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
